---
collections:
  - name: ansible.platform
    version: 2.5.0
  - name: ./collections/ansible-controller-4.6.0.tar.gz
    type: file
  - name: ansible.hub
    version: 1.0.0
  - name: ansible.eda
    version: 2.1.0
  - name: infra.controller_configuration
    version: 2.10.3
  - name: infra.ah_configuration
    version: 2.0.6
  - name: infra.eda_configuration
    version: 1.1.0
