---
- name: ansible.controller collection tests
  hosts: localhost
  
  tasks:
  - name: Setup Components
    ad_hoc_command:
      inventory: Demo Inventory
      credential: Demo Credential
      module_name: command
      module_args: echo I <3 Ansible
      wait: true
