---
- name: Configure for Ansible Product Demos
  hosts: localhost
  vars:
    controller_validate_certs: false
    controller_execution_environments:
      - name: product-demos
        image: quay.io/acme_corp/product-demos-ee:latest
    user_message: "Configuration Complete"

  tasks:
  - name: Setup Components
    include_role:
      name: infra.controller_configuration.dispatch

  - name: Print Message
    debug:
      msg: "{{ user_message }}"
    when: user_message is defined
